In [2]:
import os
os.chdir('/Users/weizheng/PycharmProjects/machinelearninginaction-master/Ch07')

In [1]:

import adaboost3_6

In [2]:
from imp import reload

In [17]:
reload(adaboost3_6)

<module 'adaboost3_6' from '/Users/weizheng/PycharmProjects/machinelearninginaction-master/Ch07/adaboost3_6.py'>

In [3]:
dat_mat, class_labels =adaboost3_6.load_simpdata()

In [11]:
reload(adaboost3_6)

<module 'adaboost3_6' from 'C:\\Users\\wei\\PycharmProjects\\python_projects\\machinelearninginaction-master\\Ch07\\adaboost3_6.py'>

In [5]:
import numpy as np

In [7]:
D = np.mat(np.ones((5,1))/5.0)

In [8]:
D

matrix([[ 0.2],
        [ 0.2],
        [ 0.2],
        [ 0.2],
        [ 0.2]])

In [13]:
 best_stump, min_error, best_class_est = adaboost3_6.build_stump(dat_mat, class_labels, D)

split: dim 0, thresh 0.90, thresh inequal: lt, the weighted erroris  0.400
split: dim 0, thresh 0.90, thresh inequal: gt, the weighted erroris  0.600
split: dim 0, thresh 1.00, thresh inequal: lt, the weighted erroris  0.400
split: dim 0, thresh 1.00, thresh inequal: gt, the weighted erroris  0.600
split: dim 0, thresh 1.10, thresh inequal: lt, the weighted erroris  0.400
split: dim 0, thresh 1.10, thresh inequal: gt, the weighted erroris  0.600
split: dim 0, thresh 1.20, thresh inequal: lt, the weighted erroris  0.400
split: dim 0, thresh 1.20, thresh inequal: gt, the weighted erroris  0.600
split: dim 0, thresh 1.30, thresh inequal: lt, the weighted erroris  0.200
split: dim 0, thresh 1.30, thresh inequal: gt, the weighted erroris  0.800
split: dim 0, thresh 1.40, thresh inequal: lt, the weighted erroris  0.200
split: dim 0, thresh 1.40, thresh inequal: gt, the weighted erroris  0.800
split: dim 0, thresh 1.50, thresh inequal: lt, the weighted erroris  0.200
split: dim 0, thresh 1.50

In [14]:
best_stump

{'dim': 0, 'ineq': 'lt', 'thresh': 1.3}

In [15]:
min_error

matrix([[ 0.2]])

In [16]:
best_class_est

array([[-1.],
       [ 1.],
       [-1.],
       [-1.],
       [ 1.]])

In [17]:
class_labels

[1.0, 1.0, -1.0, -1.0, 1.0]

In [23]:
import pandas as pd
import numpy as np

In [48]:
pd.DataFrame(best_class_est).rename(columns={0:'pred'})

pred
0  -1.0
1   1.0
2  -1.0
3  -1.0
4   1.0

In [52]:
pd.concat([pd.DataFrame(best_class_est).rename(columns={0:'pred'}), pd.DataFrame(class_labels).rename(columns={0:'true'})], axis=1)

pred  true
0  -1.0   1.0
1   1.0   1.0
2  -1.0  -1.0
3  -1.0  -1.0
4   1.0   1.0