In [1]:
import numpy as np

In [2]:
np.zeros((4,))

array([ 0.,  0.,  0.,  0.])

In [3]:
np.zeros((4,1))

array([[ 0.],
       [ 0.],
       [ 0.],
       [ 0.]])

In [4]:
a = np.zeros((4,))
b = np.zeros((4,1))

In [5]:
a.shape

(4,)

In [6]:
b.shape

(4, 1)

In [7]:
from sklearn.datasets.samples_generator import make_blobs

In [8]:
(X, y) = make_blobs(n_samples=250, n_features=2, centers=2,
                    cluster_std=1.05, random_state=42)

In [9]:
X = np.c_[np.ones((X.shape[0])), X]

In [10]:
X.shape

(250, 3)

In [13]:
W = np.zeros((3,))

In [14]:
np.dot(X, W)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0

In [16]:
def sigmoid_activation(x):
    return 1.0/(1 + np.exp(-x))

In [20]:
W = np.array([0.056, 0.583, -0.226])

In [21]:
np.dot(X, W)

array([-3.13723156,  3.02099765, -2.65086381,  2.42896803,  1.81472151,
       -3.81994329, -4.43374963, -3.38529315,  3.81527523,  2.10724168,
       -2.9523131 , -3.78105541, -3.76063491,  2.58536691, -3.46350317,
        1.94331316, -3.81718634, -3.58783864, -3.15432285,  2.1532093 ,
       -4.61237494,  2.15533305,  2.21194192, -2.39001697,  1.89180315,
       -3.97692601,  1.88604976, -3.25073345, -3.47280483, -3.26156931,
       -2.64129923, -3.94255044,  1.31771572,  2.05008873,  2.51131858,
        4.08407983,  3.2372011 , -3.47100519, -2.28210449, -4.30385514,
        2.69799899,  3.38037644, -3.33682779, -4.23782474, -2.9229456 ,
       -2.74406303,  2.23325833,  2.62734579, -3.35814551, -4.04305762,
       -2.54010868,  1.76181789,  3.01760563,  2.3047001 ,  2.30717445,
       -3.47053019,  2.55834066, -3.89018195,  1.93215582, -3.60464143,
       -3.13711617, -3.90200549,  3.84741006,  1.48131581, -4.2515967 ,
       -2.65948802, -3.79609845, -3.57224405,  2.80559703,  1.75

In [22]:
pred = sigmoid_activation(np.dot(X, W))

In [23]:
error = pred - y

In [24]:
error[:4]

array([ 0.04159735, -0.04648623,  0.06593579, -0.08099024])

In [26]:
gradient = X.transpose().dot(error)

In [27]:
gradient

array([ -8.27885818, -60.21465454,  11.62887089])

In [32]:
gradient.shape

(3,)

In [29]:
error.shape

(250,)

In [30]:
X.shape

(250, 3)

In [34]:
X.T.shape

(3, 250)