In [1]:
import numpy as np
import urllib

In [4]:
url = 'http://archive.ics.uci.edu/ml/machine-learning-databases/pima-indians-diabetes/pima-indians-diabetes.data'

In [5]:
raw_data = urllib.urlopen(url)

In [8]:
dataset = np.loadtxt(raw_data, delimiter = ',')

In [9]:
dataset.dtype

dtype('float64')

In [13]:
dataset[:3,]

array([[   6.   ,  148.   ,   72.   ,   35.   ,    0.   ,   33.6  ,
           0.627,   50.   ,    1.   ],
       [   1.   ,   85.   ,   66.   ,   29.   ,    0.   ,   26.6  ,
           0.351,   31.   ,    0.   ],
       [   8.   ,  183.   ,   64.   ,    0.   ,    0.   ,   23.3  ,
           0.672,   32.   ,    1.   ]])

In [16]:
X = dataset[:,0:7]

In [17]:
y = dataset[:,8]

In [18]:
# 数据归一化(Data Normalization)

In [19]:
from sklearn import preprocessing

In [20]:
normalized_X = preprocessing.normalize(X)

In [22]:
standardized_X = preprocessing.scale(X)

In [23]:
#特征选择(Feature Selection)

In [24]:
from sklearn import metrics
from sklearn.ensemble import ExtraTreesClassifier

In [25]:
model = ExtraTreesClassifier()

In [26]:
model.fit(X,y)

ExtraTreesClassifier(bootstrap=False, class_weight=None, criterion='gini',
           max_depth=None, max_features='auto', max_leaf_nodes=None,
           min_impurity_split=1e-07, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           n_estimators=10, n_jobs=1, oob_score=False, random_state=None,
           verbose=0, warm_start=False)

In [27]:
print model.feature_importances_

[ 0.1264256   0.27459126  0.13046592  0.08727469  0.0807216   0.15385048
  0.14667045]


In [28]:
#算法选择(Algorithm)

In [29]:
#model-LogisticRegression
from sklearn.linear_model import LogisticRegression

In [30]:
model = LogisticRegression()

In [31]:
model.fit(X,y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [32]:
expected = y
predicted = model.predict(X)

In [35]:
#summarize the fit of the model
print metrics.classification_report(expected, predicted)
print metrics.confusion_matrix(expected,predicted)

             precision    recall  f1-score   support

        0.0       0.79      0.89      0.84       500
        1.0       0.74      0.55      0.63       268

avg / total       0.77      0.77      0.77       768

[[447  53]
 [120 148]]


In [36]:
#model- Naive Bayes
from sklearn.naive_bayes import GaussianNB

In [37]:
model = GaussianNB()

In [38]:
model.fit(X,y)

GaussianNB(priors=None)

In [39]:
expected =y
predicted = model.predict(X)

In [41]:
#summarize the fit of the model
print metrics.classification_report(expected, predicted)
print metrics.confusion_matrix(expected, predicted)

             precision    recall  f1-score   support

        0.0       0.80      0.86      0.83       500
        1.0       0.69      0.60      0.64       268

avg / total       0.76      0.77      0.76       768

[[429  71]
 [108 160]]


In [42]:
#model-KNeignbor
from sklearn.neighbors import KNeighborsClassifier

In [44]:
model = KNeighborsClassifier()

In [45]:
model.fit(X, y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [46]:
expected = y
predicted = model.predict(X)

In [48]:
print metrics.classification_report(expected, predicted)
print metrics.confusion_matrix(expected, predicted)

             precision    recall  f1-score   support

        0.0       0.82      0.90      0.86       500
        1.0       0.77      0.63      0.69       268

avg / total       0.80      0.80      0.80       768

[[448  52]
 [ 98 170]]


In [50]:
#model-CART
from sklearn.tree import DecisionTreeClassifier

In [51]:
model = DecisionTreeClassifier()

In [52]:
model.fit(X,y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [53]:
expected = y
predicted = model.predict(X)

In [55]:
print metrics.classification_report(expected, predicted)
print metrics.confusion_matrix(expected, predicted)

             precision    recall  f1-score   support

        0.0       1.00      1.00      1.00       500
        1.0       1.00      1.00      1.00       268

avg / total       1.00      1.00      1.00       768

[[500   0]
 [  0 268]]


In [56]:
#model-svm
from sklearn.svm import SVC

In [57]:
model = SVC()

In [58]:
model.fit(X,y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [60]:
expected = y
predicted = model.predict(X)

In [61]:
print metrics.classification_report(expected, predicted)
print metrics.confusion_matrix(expected, predicted)

             precision    recall  f1-score   support

        0.0       1.00      1.00      1.00       500
        1.0       1.00      1.00      1.00       268

avg / total       1.00      1.00      1.00       768

[[500   0]
 [  0 268]]


In [ ]:
#优化参数--coming...